name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build github.com/downflux/orca
      run: go build -v github.com/downflux/orca/...

    - name: Test github.com/downflux/orca
      run: go test -v github.com/downflux/orca/... -bench .
