name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build github.com/downflux/go-orca
      run: go build github.com/downflux/go-orca/...

    - name: Vet github.com/downflux/go-orca
      run: go vet github.com/downflux/go-orca/...

    - name: Test github.com/downflux/go-orca
      run: go test github.com/downflux/go-orca/... -bench . -benchmem
